select *from gravadora;
insert into gravadora(NOME_GRAVADORA,ENDERECO_GRAVADORA,TELEFONE_GRAVADORA,CONTATO,URL) values("EMI","Rod. Duarte km 299","6334127775","Pedro","www.emi-music.com.br");
insert into gravadora(NOME_GRAVADORA,ENDERECO_GRAVADORA,TELEFONE_GRAVADORA,CONTATO,URL) values("POLYGRAM","Rua 25 de março","6331238888","Lucas","www.polygram.com.br");


select *from CD;
insert into CD(nome,preco_venda,data_lancamento,gravadora_codigo_gravadora) values('Mais do mesmo',15.00,'2014-12-12',1);                                                                                                                             
insert into CD(nome,preco_venda,data_lancamento,gravadora_codigo_gravadora) values('Bate Boca',12.00,'2014-01-01',2);                                                                                                                             


select *from musica;
insert into musica(nome_musica,duracao) values('Será','00:02:28');
insert into musica(nome_musica,duracao) values('Ainda é cedo','00:03:55');
insert into musica(nome_musica,duracao) values('Geração coca-cola','00:02:20');
insert into musica(nome_musica,duracao) values('Eduardo e Mônica','00:04:32');
insert into musica(nome_musica,duracao) values('Tempo Perdido','00:05:00');
insert into musica(nome_musica,duracao) values('Índios','00:04:23');
insert into musica(nome_musica,duracao) values('Que País é este','00:03:04');
insert into musica(nome_musica,duracao) values('Faroeste Caboclo','00:09:03');
insert into musica(nome_musica,duracao) values('Há Tempos','00:03:16');
insert into musica(nome_musica,duracao) values('Pais e Filhos','00:05:06');
insert into musica(nome_musica,duracao) values('Meninas e meninas','00:03:22');
insert into musica(nome_musica,duracao) values('Vento no litoral','00:06:05');
insert into musica(nome_musica,duracao) values('Perfeição','00:04:35');
insert into musica(nome_musica,duracao) values('Giz','00:03:20');
insert into musica(nome_musica,duracao) values('Dezesseis','00:05:28');
insert into musica(nome_musica,duracao) values('Antes das seis','00:03:09');
insert into musica(nome_musica,duracao) values('Meninos eu vi','00:03:25');
insert into musica(nome_musica,duracao) values('Eu te amo','00:03:06');
insert into musica(nome_musica,duracao) values('Piano na mangueira','00:02:23');
insert into musica(nome_musica,duracao) values('A violeira','00:02:54');
insert into musica(nome_musica,duracao) values('Anos Dourados','00:02:56');
insert into musica(nome_musica,duracao) values('Olha Maria','00:03:55');
insert into musica(nome_musica,duracao) values('Biscate','00:03:20');
insert into musica(nome_musica,duracao) values('Retrato em preto e','00:03:03');
insert into musica(nome_musica,duracao) values('Falando de amor','00:03:20');
insert into musica(nome_musica,duracao) values('Pois é','00:02:48');
insert into musica(nome_musica,duracao) values('Noite dos mascarados','00:02:42');
insert into musica(nome_musica,duracao) values('Sabiá','00:03:20');
insert into musica(nome_musica,duracao) values('Imagina','00:02:52');
insert into musica(nome_musica,duracao) values('Bate-Boca','00:04:41');

select * from item_CD;
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(1,1,1,1);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(2,2,1,2);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(3,3,1,3);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(4,4,1,4);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(5,5,1,5);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(6,6,1,6);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(7,7,1,7);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(8,8,1,8);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(9,9,1,9);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(10,10,1,10);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(11,11,1,11);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(12,12,1,12);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(13,13,1,13);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(14,14,1,14);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(15,15,1,15);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(16,16,1,16);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(17,1,2,17);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(18,2,2,18);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(19,3,2,19);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(20,4,2,20);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(21,5,2,21);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(22,6,2,22);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(23,7,2,23);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(24,8,2,24);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(25,9,2,25);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(26,10,2,26);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(27,11,2,27);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(28,12,2,28);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(29,13,2,29);
insert into item_CD(codigo_item_cd,numero_faixa,cd_codigo_cd,musica_codigo_musica) values(30,14,2,30);